apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    version: "1.0"
spec:
  containers:
    - name: app
      image: nginx:1.24
      env:
        - name: ENV_VAR
          value: test-value
      resources:
        limits:
          memory: 128Mi
          cpu: 500m
        requests:
          memory: 64Mi
          cpu: 250m
      ports:
        - containerPort: 80
          protocol: TCP
