#!/usr/bin/env bash

echo -e "AI CLI tools overview"
echo -e ""
echo -e "All AI coding agents are managed via Brewfile:"
echo -e ""
echo -e "  Homebrew formulas:"
echo -e "    - opencode    (brew sst/tap/opencode)"
echo -e "    - gemini-cli  (brew gemini-cli)       → binary: gemini"
echo -e "    - kimi-cli    (brew kimi-cli)          → binary: kimi"
echo -e ""
echo -e "  Homebrew casks:"
echo -e "    - claude-code (cask claude-code)       → binary: claude"
echo -e "    - codex       (cask codex)             → binary: codex"
echo -e ""
echo -e "Run 'brew bundle' from the dotfiles root to install all tools."
echo -e ""
echo -e "First-use authentication:"
echo -e "  - claude: launches interactive auth on first run"
echo -e "  - opencode: launches interactive auth on first run"
echo -e "  - gemini: run 'gemini' to authenticate with Google"
echo -e "  - codex: run 'codex' to authenticate with OpenAI"
echo -e "  - kimi: run 'kimi /login' to authenticate with Moonshot AI"
