# Set settings for fzf
zstyle ':zim:plugins:fzf' no-height 'yes'
zstyle ':zim:plugins:fzf' no-reverse 'yes'

# Set the theme for fzf
zstyle ':zim:plugins:fzf' color-fg '-1'
zstyle ':zim:plugins:fzf' color-fg+ '#d0d0d0'
zstyle ':zim:plugins:fzf' color-bg '-1'
zstyle ':zim:plugins:fzf' color-bg+ '#262626'
zstyle ':zim:plugins:fzf' color-hl '#f38ba8'
zstyle ':zim:plugins:fzf' color-hl+ '#5fd7ff'
zstyle ':zim:plugins:fzf' color-info '#cba6f7'
zstyle ':zim:plugins:fzf' color-marker '#b4befe'
zstyle ':zim:plugins:fzf' color-prompt '#cba6f7'
zstyle ':zim:plugins:fzf' color-spinner '#f5e0dc'
zstyle ':zim:plugins:fzf' color-pointer '#5fd7ff'
zstyle ':zim:plugins:fzf' color-header '#f38ba8'
zstyle ':zim:plugins:fzf' color-gutter '#1e1e2e'
zstyle ':zim:plugins:fzf' color-border '#585b70'
zstyle ':zim:plugins:fzf' color-label '#aeaeae'
zstyle ':zim:plugins:fzf' color-query '#d9d9d9'
zstyle ':zim:plugins:fzf' border 'rounded'
zstyle ':zim:plugins:fzf' preview-window 'border-rounded'
zstyle ':zim:plugins:fzf' prompt '  '
zstyle ':zim:plugins:fzf' marker ''
zstyle ':zim:plugins:fzf' pointer '⏽'
zstyle ':zim:plugins:fzf' scrollbar '│'
zstyle ':zim:plugins:fzf' layout 'reverse'