name: Workflow with actionlint errors
# =============================================================================
# GitHub Actions Test File with Intentional Errors
# Tests for actionlint
# =============================================================================

# Error: Invalid trigger event
on:
  push_request:  # Should be pull_request
    branches: [ main ]
  
  # Error: Invalid event type
  published:  # Should be under 'release'
    types: [ created ]
  
  # Error: Schedule with invalid cron
  schedule:
    - cron: '60 25 * * *'  # Invalid: 60 minutes, 25 hours
    - cron: '0 0 31 2 *'  # Invalid: Feb 31st doesn't exist
  
  # Error: Unknown event
  unknown_event:
    branches: [ main ]

# Error: Invalid workflow dispatch input type
  workflow_dispatch:
    inputs:
      environment:
        type: text  # Should be 'string', not 'text'
        required: yes  # Should be boolean true, not yes
        default: staging
      
      number:
        type: integer  # Should be 'number', not 'integer'

# Error: Missing required fields
jobs:
  # Error: Job without runs-on
  missing-runs-on:
    steps:
      - uses: actions/checkout@v4

  # Error: Invalid runner
  invalid-runner:
    runs-on: ubuntu-latest-invalid  # Invalid runner name
    steps:
      - run: echo "test"

  # Error: Matrix with issues
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
        # Error: Exclude with non-existent combination
        exclude:
          - node: 19  # 19 not in matrix
            os: ubuntu-latest
    steps:
      - run: echo "Node ${{ matrix.nodejs }}"  # Wrong variable name

  # Error: Invalid needs reference
  dependent:
    runs-on: ubuntu-latest
    needs: non-existent-job  # Job doesn't exist
    steps:
      - run: echo "test"

  # Error: Circular dependency
  circular1:
    runs-on: ubuntu-latest
    needs: circular2
    steps:
      - run: echo "test"

  circular2:
    runs-on: ubuntu-latest  
    needs: circular1  # Circular dependency
    steps:
      - run: echo "test"

  # Error: Various step errors
  step-errors:
    runs-on: ubuntu-latest
    steps:
      # Error: Both run and uses
      - name: Invalid step
        run: echo "test"
        uses: actions/checkout@v4  # Can't have both

      # Error: Neither run nor uses
      - name: Empty step
        # No run or uses

      # Error: Invalid uses syntax
      - uses: actions/checkout  # Missing version
      - uses: actions/checkout@  # Empty version
      - uses: actions/checkout@v99  # Non-existent version
      - uses: ./local-action  # Local action without checkout first
      - uses: invalid@syntax@v1  # Invalid syntax

      # Error: Invalid with parameters
      - uses: actions/checkout@v4
        with:
          unknown-param: value  # Parameter doesn't exist
          fetch-depth: "not-a-number"  # Wrong type

      # Error: Invalid if condition
      - name: Bad condition
        if: ${{ always() && never() }}  # never() doesn't exist
        run: echo "test"

      # Error: Syntax error in expression
      - name: Syntax error
        if: ${{ github.event == 'push' }}  # Should be github.event_name
        run: echo "test"

      # Error: Invalid shell
      - name: Invalid shell
        shell: invalid-shell  # Not a valid shell
        run: echo "test"

      # Error: Windows-specific command on Linux
      - name: Windows command on Linux
        run: dir  # Windows command, should use ls

      # Error: Invalid working directory
      - name: Invalid working directory
        working-directory: /non/existent/path
        run: echo "test"

      # Error: Invalid continue-on-error
      - name: Invalid continue
        continue-on-error: "true"  # Should be boolean, not string
        run: exit 1

      # Error: Invalid timeout
      - name: Invalid timeout
        timeout-minutes: "30"  # Should be number, not string
        run: sleep 60

      # Error: Missing required input
      - uses: actions/setup-node@v4
        # Missing required 'node-version' input

      # Error: Invalid secret reference
      - name: Invalid secret
        run: echo ${{ secret.TOKEN }}  # Should be secrets.TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKE }}  # Typo in secret name

      # Error: Using deprecated commands
      - name: Deprecated commands
        run: |
          echo "::set-env name=VAR::value"  # Deprecated
          echo "::add-path::/usr/local/bin"  # Deprecated
          echo "::save-state name=state::value"  # Deprecated

  # Error: Invalid environment
  environment-job:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: not-a-url  # Invalid URL format
    steps:
      - run: echo "deploy"

  # Error: Invalid permissions
  permissions-job:
    runs-on: ubuntu-latest
    permissions:
      read: contents  # Wrong format, should be contents: read
      unknown-permission: write  # Invalid permission
    steps:
      - run: echo "test"

  # Error: Invalid outputs
  outputs-job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.nonexistent.outputs.value }}  # Step doesn't exist
      invalid: ${{ invalid.syntax }}  # Invalid syntax
    steps:
      - id: generate
        run: echo "::set-output name=value::test"  # Deprecated syntax

  # Error: Invalid services
  services-job:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        # Error: Missing required env for postgres
        ports:
          - 5432  # Should be 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10
          # Missing time unit (should be 10s)
    steps:
      - run: echo "test"

  # Error: Invalid container
  container-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      env:
        KEY: ${{ undefined.variable }}  # Undefined variable
      volumes:
        - /invalid:volume:syntax  # Invalid syntax
      options: --invalid-option  # Invalid option
    steps:
      - run: echo "test"

  # Error: Invalid concurrency
  concurrency-job:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: "true"  # Should be boolean
    steps:
      - run: echo "test"

  # Error: Invalid defaults
  defaults-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: powershell  # PowerShell on Linux
        working-directory: ./nonexistent
    steps:
      - run: echo "test"

  # Error: Invalid strategy
  strategy-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: "2"  # Should be number
      fail-fast: "false"  # Should be boolean
      matrix:
        version: [1, 2, 3]
    steps:
      - run: echo "${{ matrix.versions }}"  # Wrong variable name

# Error: Global env with issues
env:
  GLOBAL: value
  INVALID: ${{ secrets.DOESNT_EXIST }}
  SYNTAX_ERROR: ${{ github. }}  # Incomplete expression

# Error: Invalid workflow-level permissions
permissions:
  issues: true  # Should be read/write, not boolean
  pull-requests: none  # Should be read/write/none as string

# Error: Invalid defaults at workflow level
defaults:
  run:
    shell: cmd  # cmd not available on default runners
    
# Error: Invalid concurrency at workflow level
concurrency:
  group: 
  # Empty group

# Error: Reusable workflow issues
on:
  workflow_call:
    inputs:
      param:
        type: string
        required: true
        # Missing description
    secrets:
      secret:
        required: yes  # Should be boolean
    outputs:
      result:
        description: "Result"
        # Missing value

# Error: Workflow name issues
name:  # Empty name

# Error: Invalid on.push configuration
on:
  push:
    branches:
      - refs/heads/main  # Should be just 'main'
    tags:
      - v*.*.*  # Valid but might not work as expected
    paths:
      - **.yml  # Should be '**.yml' or '**/*.yml'
    paths-ignore:
      - **.md
    # Can't have both paths and paths-ignore

# Error: Invalid on.pull_request
on:
  pull_request:
    types: [opened, close]  # Should be 'closed', not 'close'
    
# Error: Duplicate on events (can't actually have duplicate keys in YAML)

# Error: Job with invalid ID
123-invalid-job-id:  # Can't start with number
  runs-on: ubuntu-latest
  steps:
    - run: echo "test"

"job with spaces":  # Spaces in job ID
  runs-on: ubuntu-latest
  steps:
    - run: echo "test"

# Error: Comments in expressions
comment-job:
  runs-on: ubuntu-latest
  steps:
    - name: Comment in expression
      if: ${{ true # comment }}  # Comments not allowed in expressions
      run: echo "test"

# Error: Invalid artifact actions
artifact-job:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        # Missing 'path' parameter
        
    - uses: actions/download-artifact@v3
      with:
        name: different-artifact  # Artifact doesn't exist in this workflow
        
# Error: Invalid cache action
cache-job:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        # Missing 'key' parameter

# Error: Checkout with invalid parameters  
checkout-job:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: all  # Should be number or 0
        submodules: yes  # Should be boolean or 'recursive'

# Error: File doesn't end with newline
